/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as DealbreakersRouteImport } from './routes/dealbreakers'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WeightingRouteImport } from './routes/weighting'
import { Route as AuthenticatedClaimAdminRouteImport } from './routes/_authenticated/claim-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DealbreakersRoute = DealbreakersRouteImport.update({
  id: '/dealbreakers',
  path: '/dealbreakers',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightingRoute = WeightingRouteImport.update({
  id: '/weighting',
  path: '/weighting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClaimAdminRoute = AuthenticatedClaimAdminRouteImport.update({
  id: '/claim-admin',
  path: '/claim-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm': typeof ConfirmRoute
  '/dealbreakers': typeof DealbreakersRoute
  '/rating': typeof RatingRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/weighting': typeof WeightingRoute
  '/claim-admin': typeof AuthenticatedClaimAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm': typeof ConfirmRoute
  '/dealbreakers': typeof DealbreakersRoute
  '/rating': typeof RatingRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/weighting': typeof WeightingRoute
  '/claim-admin': typeof AuthenticatedClaimAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confirm': typeof ConfirmRoute
  '/dealbreakers': typeof DealbreakersRoute
  '/rating': typeof RatingRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/weighting': typeof WeightingRoute
  '/_authenticated/claim-admin': typeof AuthenticatedClaimAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirm'
    | '/dealbreakers'
    | '/rating'
    | '/report'
    | '/reset-password'
    | '/weighting'
    | '/claim-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirm'
    | '/dealbreakers'
    | '/rating'
    | '/report'
    | '/reset-password'
    | '/weighting'
    | '/claim-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confirm'
    | '/dealbreakers'
    | '/rating'
    | '/report'
    | '/reset-password'
    | '/weighting'
    | '/_authenticated/claim-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfirmRoute: typeof ConfirmRoute
  DealbreakersRoute: typeof DealbreakersRoute
  RatingRoute: typeof RatingRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WeightingRoute: typeof WeightingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealbreakers': {
      id: '/dealbreakers'
      path: '/dealbreakers'
      fullPath: '/dealbreakers'
      preLoaderRoute: typeof DealbreakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weighting': {
      id: '/weighting'
      path: '/weighting'
      fullPath: '/weighting'
      preLoaderRoute: typeof WeightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/claim-admin': {
      id: '/_authenticated/claim-admin'
      path: '/claim-admin'
      fullPath: '/claim-admin'
      preLoaderRoute: typeof AuthenticatedClaimAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClaimAdminRoute: typeof AuthenticatedClaimAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClaimAdminRoute: AuthenticatedClaimAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfirmRoute: ConfirmRoute,
  DealbreakersRoute: DealbreakersRoute,
  RatingRoute: RatingRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WeightingRoute: WeightingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
